services:

  postgres:
    image: postgres:16
    container_name: acme-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: acme
      POSTGRES_USER: acme_user
      POSTGRES_PASSWORD: acme_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - acme-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - acme-network

  flyway:
    image: flyway/flyway:10
    container_name: acme-flyway
    command: -url=jdbc:postgresql://postgres:5432/acme -user=acme_user -password=acme_pass -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - acme-network
    depends_on:
      - postgres

  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: acme-wiremock
    command: --global-response-templating
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      - acme-network

volumes:
  postgres_data:

networks:
  acme-network:
    driver: bridge
