version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: acme-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: acme
      POSTGRES_USER: acme_user
      POSTGRES_PASSWORD: acme_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - acme-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - acme-network

  flyway:
    image: flyway/flyway:10
    container_name: acme-flyway
    command: -url=jdbc:postgresql://postgres:5432/acme -user=acme_user -password=acme_pass -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - acme-network
    depends_on:
      - postgres

  wiremock:
    image: wiremock/wiremock:3.2.0
    container_name: acme-wiremock
    command: --global-response-templating
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      - acme-network

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: acme-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    restart: unless-stopped
    networks:
      - acme-network

  grafana:
    image: grafana/grafana:10.0.0
    container_name: acme-grafana
    ports:
      - '3000:3000'
    networks:
      - acme-network
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/ # Adicione esta linha
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: acme-zipkin
    ports:
      - '9411:9411'
    networks:
      - acme-network
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:

networks:
  acme-network:
    driver: bridge