{
 "title": "ACME - Dashboard de Observabilidade",
 "tags": [
  "acme",
  "spring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total de Requisições por Segundo (RPS)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"spring-application\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latência P95 (Tempo de Resposta)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"spring-application\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Contagem de Requisições por Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"spring-application\"}[5m])) by (status)"
    }
   ]
  },
  {
   "title": "Threads Ativas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"spring-application\"}"
    }
   ]
  }
 ]
}